### ISSUE TITLE
请问如何获取CC3M的图像数据呢？

### ISSUE THREAD

**Issue by Wenwen717** [lyq312318224/MLLMs-Augmented#1]
感谢您开源如此出色工作！

我想问下，我该如何获取CC3M数据集对应的图像数据，我需要根据数据中的url一个个下载吗？

**Comment by Yanqing0327** [comment]
感谢对我们工作的关注！可以使用img2dataset下载图像，具体可以参考https://github.com/rom1504/img2dataset/blob/main/dataset_examples/cc3m.md
